version: "3"
services:

  site:
    build: 
      context: .
      args:
        bulma_version: ${BULMA_VERSION:-0.7.4}
    image: mysite:latest
    expose:
      - "8043"
    labels:
      - traefik.backend=$TRAEFIK_BACKEND
      - traefik.frontend.rule=Host:$TRAEFIK_URL
